---
apiVersion: v1
kind: Service
metadata:
  name: elasticml-elasticsearch
spec:
  selector:
    app: elasticml-elasticsearch
  ports:
  - name: api-port
    port: 9200
    targetPort: 9200
    protocol: TCP
  - name: cluster-port
    port: 9300
    targetPort: 9300
    protocol: TCP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticml-elasticsearch
  labels:
    app: elasticml-elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticml-elasticsearch
  template:
    metadata:
      labels:
        app: elasticml-elasticsearch
    spec:
      containers:
      - name: elasticml-elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
        ports:
        - containerPort: 9200
        - containerPort: 9300
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: elasticsearch-data
        - mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          name: elasticsearch-config
        - mountPath: /usr/share/elasticsearch/config/jvm.options
          name: elasticsearch-jvm
      volumes:
      - name: elasticsearch-data
        hostPath:
          path: /mnt/elastic_volume/elasticsearch/data
          type: DirectoryOrCreate
      - name: elasticsearch-config
        hostPath:
          path: /mnt/elastic_volume/elasticsearch/config/elasticsearch.yml
          type: File
      - name: elasticsearch-jvm
        hostPath:
          path: /mnt/elastic_volume/elasticsearch/config/jvm.options
          type: File
