---
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: elasticml-elasticsearch
    namespace: kube-system
    labels:
      k8s-app: kibana
  data:
    elasticsearch.yml: |-
      ---
      http.host: 0.0.0.0
      discovery.type: single-node
      xpack.security.enabled: true
    jvm.options: |-
      -Dlog4j2.disable.jmx=true
      -Xms2048m
      -Xmx2048m

---
apiVersion: v1
kind: Service
metadata:
  name: elasticml-elasticsearch
  namespace: kube-system
spec:
  selector:
    app: elasticml-elasticsearch
  ports:
  - name: api-port
    port: 9200
    targetPort: 9200
    protocol: TCP
  - name: cluster-port
    port: 9300
    targetPort: 9300
    protocol: TCP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticml-elasticsearch
  namespace: kube-system
  labels:
    app: elasticml-elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticml-elasticsearch
  template:
    metadata:
      labels:
        app: elasticml-elasticsearch
    spec:
      containers:
      - name: elasticml-elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
        ports:
        - containerPort: 9200
        - containerPort: 9300
        volumeMounts:
        - name: config
          mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          subPath: elasticsearch.yml
        - name: config
          mountPath: /usr/share/elasticsearch/config/jvm.options
          subPath: jvm.options
      volumes:
      - name: config
        configMap:
          name: elasticml-elasticsearch

