---
apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticml-kibana
  namespace: default
  labels:
    k8s-app: kibana
data:
  kibana.yml: |-
    ---
    server.name: "*"
    server.host: "0.0.0.0"
    xpack.security.encryptionKey: LTJRRHr81rnBY84WQ1kCNIvXa3rcAEnd
    xpack.security.sessionTimeout: 600000
    elasticsearch.hosts: http://elasticml-elasticsearch:9200
    elasticsearch.username: kibana
    elasticsearch.password: ZfEcQ5ILTalTp1cWGeNj

---
apiVersion: v1
kind: Service
metadata:
  name: elasticml-kibana
spec:
  type: NodePort
  selector:
    app: elasticml-kibana
  ports:
  - port: 5601
    targetPort: 5601
    protocol: TCP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticml-kibana
  labels:
    app: elasticml-kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticml-kibana
  template:
    metadata:
      labels:
        app: elasticml-kibana
    spec:
      containers:
      - name: elasticml-kibana
        image: docker.elastic.co/kibana/kibana:7.6.1
        ports:
        - containerPort: 5601
        volumeMounts:
        - name: config
          mountPath: /usr/share/kibana/config/
      volumes:
      - name: config
        configMap:
          name: elasticml-kibana
          items:
            - key: kibana.yml
              path: kibana.yml
