---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  org: elasticml

resources:
- elasticsearch.yml
- kibana.yml
- logstash.yml
- filebeat.yml
- metricbeat.yml
- logger.yml