---
apiVersion: batch/v1
kind: Job
metadata:
  name: elasticml-logger
spec:
  template:
    metadata:
      name: elasticml-logger
    spec:
      containers:
      - name: elasticml-logger
        image: kugtong33/random-logger:2
      restartPolicy: Never
  backoffLimit: 5
