---
apiVersion: v1
kind: Service
metadata:
  name: elasticml-logstash
spec:
  type: NodePort
  selector:
    app: elasticml-logstash
  ports:
  - port: 5044
    targetPort: 5044
    protocol: TCP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticml-logstash
  labels:
    app: elasticml-logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticml-logstash
  template:
    metadata:
      labels:
        app: elasticml-logstash
    spec:
      containers:
      - name: elasticml-logstash
        image: docker.elastic.co/logstash/logstash:7.6.1
        ports:
        - containerPort: 5044
        volumeMounts:
        - mountPath: /usr/share/logstash/config/logstash.yml
          name: logstash-config-main
        - mountPath: /usr/share/logstash/config/pipelines.yml
          name: logstash-config-pipeline
        - mountPath: /usr/share/logstash/config/jvm.options
          name: logstash-config-jvm
        - mountPath: /usr/share/logstash/pipeline
          name: logstash-pipeline
        - mountPath: /usr/share/logstash/queue
          name: logstash-queue
      volumes:
      - name: logstash-config-main
        hostPath:
          path: /mnt/elastic_volume/logstash/config/logstash.yml
          type: File
      - name: logstash-config-pipeline
        hostPath:
          path: /mnt/elastic_volume/logstash/config/pipelines.yml
          type: File
      - name: logstash-config-jvm
        hostPath:
          path: /mnt/elastic_volume/logstash/config/jvm.options
          type: File
      - name: logstash-pipeline
        hostPath:
          path: /mnt/elastic_volume/logstash/pipeline
          type: Directory
      - name: logstash-queue
        hostPath:
          path: /mnt/elastic_volume/logstash/queue
          type: Directory
