---
apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticml-logstash
  namespace: default
  labels:
    k8s-app: logstash
data:
  jvm.options: |-
    -Xms1024m
    -Xmx1024m
  logstash.yml: |-
    ---
    pipeline.batch.size: 64
    http.host: '0.0.0.0'
    path.queue: '/usr/share/logstash/queue'
  pipelines.yml: |-
    ---
    - pipeline.id: elasticml-elasticsearch
      path.config: "/usr/share/logstash/pipeline/elasticml.elasticsearch.conf"
      pipeline.workers: 1
      queue.type: persisted
  elasticml.elasticsearch.conf: |-
    input {
      beats {
        client_inactivity_timeout => 10000
        ssl => false
        port => 5044
      }
    }

    filter {
      grok {
        match => {
          "message" => "%{TIMESTAMP_ISO8601:timestamp} %{WORD:level}:(?<scope>([a-zA-Z0-9\-_:.]+)(,[a-zA-Z0-9\-_:.]+)*) %{GREEDYDATA:body}"
        }
      }

      mutate {
        split => { "scope" => "," }
      }

      mutate {
        add_tag => [ "elasticml" ]
      }

      json {
        source => "body"
        skip_on_invalid_json => true
        target => "body"
      }

      mutate {
        remove_field => [ "agent", "message", "input", "ecs", "log", "stream", "host" ]
      }
    }

    output {
      elasticsearch {
        hosts => ['http://elasticml-elasticsearch:9200']
        user => "elastic"
        password => "1Ww9FzboZVPwocDjm0wk"
        index => "elasticml-%{+YYYY.MM.dd}"
      }
    }

---
apiVersion: v1
kind: Service
metadata:
  name: elasticml-logstash
spec:
  selector:
    app: elasticml-logstash
  ports:
  - port: 5044
    targetPort: 5044
    protocol: TCP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticml-logstash
  labels:
    app: elasticml-logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticml-logstash
  template:
    metadata:
      labels:
        app: elasticml-logstash
    spec:
      containers:
      - name: elasticml-logstash
        image: docker.elastic.co/logstash/logstash:7.6.1
        ports:
        - containerPort: 5044
        volumeMounts:
        - name: config
          mountPath: /usr/share/logstash/config
        - name: pipeline
          mountPath: /usr/share/logstash/pipeline
      volumes:
      - name: config
        configMap:
          name: elasticml-logstash
          items:
            - key: jvm.options
              path: jvm.options
            - key: logstash.yml
              path: logstash.yml
            - key: pipelines.yml
              path: pipelines.yml
      - name: pipeline
        configMap:
          name: elasticml-logstash
          items:
            - key: elasticml.elasticsearch.conf
              path: elasticml.elasticsearch.conf
